apiVersion: v1
kind: PersistentVolume
metadata:
  name: "deploy-volume"
  labels:
    type: local
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /data/deploy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "deploy-pv-claim"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  volumeName: "deploy-volume"
  resources:
    requests:
      storage: "20Gi"
